### PR TITLE
added azure cli az remove tag description

### PR DESCRIPTION
**Pull request by ChrisIIx**
added a way to remove a tag value using Azure CLI

### CODE REVIEW

**Comment by fboucher** [comment]
Hey @ChrisIIx!
Thank you for your PR. However there is a typo ( a "e" is missing) and the command is not working when there is multiple resources with that tag.

Maybe if you add a loop 

```
Get all tag "expireOn"
For each tag in tags
   az tag remove-value ....
```

**Comment by ChrisIIx** [comment]
Hi @FBoucher,

thank you very much for Notification, Sorry for the spelling mistake, must have slipped for me.
I have added a loop, which searches for any specific tag + value and afterwards remove the value one by one. Hope this helps

**Comment by fboucher** [comment]
After all this time... sorry for the delay. Thank you @ChrisIIx

**Comment by fboucher** [comment]
@all-contributors add @ChrisIIx for doc, code

**Pull request merged**
