### PR TITLE
Add the role assignment in the deployment

### LINKED ISSUE #3: Add the Role Assignment in the deployment of the Azure Function version
Right now the role assignment is done manualy after the deployment. It would be great to have it part of the 1-click experience.

### PR DESCRIPTION
**Pull request by alexkhil**
Resolves #3 

- Added contributor role to Azure Function App using ARM template.
- Updated README.md of Azure Function App according to ARM template changes.

@FBoucher

### CODE REVIEW

**Comment by fboucher** [comment]
That looks amazing, I will try that and merge it if everything is working.

- [ ] The contributorRoleId was static, it should be random

**Comment by alexkhil** [comment]
**contributorRoleId** is id of build-in azure contributor role.
image

**Comment by FBoucher** [comment]
@all-contributor add @alexkhil for code

**Comment by fboucher** [comment]
@all-contributors add @alexkhil for code

**Comment by fboucher** [comment]
Great job @alexkhil  thank you for your contribution

**Pull request merged**
